name: linked-list
version: 0.1.0.3

dependencies:
  - base

library:
  exposed-modules:
  - Deque

  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - stm

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - linked-list
      - hspec

benchmarks:
  deque-bench:
    main: Bench.hs
    source-dirs: benchmark
    dependencies:
      - linked-list
      - criterion
    ghc-options:
      - -O2

